# Generated by Django 5.1.6 on 2025-04-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
