# Generated by Django 5.1.6 on 2026-01-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_property_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('commercial', 'Коммерческая'), ('land', 'Земельный участок')], max_length=20, verbose_name='Тип недвижимости'),
        ),
    ]
