# Generated by Django 5.1.2 on 2026-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_comment_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='certificate_link',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на PDF файл или страницу с аттестатом', max_length=500, null=True, verbose_name='Ссылка на аттестат'),
        ),
    ]
