# Generated by Django 5.1.2 on 2026-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_teammember_certificate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=10, verbose_name='Тип сделки'),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='КУ (коммунальные услуги)'),
        ),
    ]
