# Generated by Django 5.1.2 on 2026-02-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_property_deal_type_property_utilities_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=10, verbose_name='Тип сделки'),
        ),
    ]
