# Generated by Django 5.1.2 on 2026-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_property_deal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('commercial', 'Коммерческая'), ('land', 'Земельный участок'), ('room', 'Комната')], max_length=20, verbose_name='Тип недвижимости'),
        ),
    ]
